### ISSUE TITLE
Create conda recipe

### ISSUE THREAD

**Issue by mbhall88** [scikit-hep/histoprint#15]
It would be nice to use this tool in a reproducible way such as `conda`.

**Comment by ast0815** [comment]
I have never worked with Conda before. Seems like you are already on it?

**Comment by mbhall88** [comment]
> I have never worked with Conda before. Seems like you are already on it?

It seems #16 means the conda recipe won't build on windows. Once #17 is merged if you could make a new release (v1.4.1 I guess?) this should fix the problem and we can get the conda recipe merged.

**Comment by ast0815** [comment]
Done.

**Comment by mbhall88** [comment]
Conda recipe is live https://anaconda.org/conda-forge/histoprint

I guess you might want to add a line to the README with something like `conda install -c conda-forge histoprint`
