### ISSUE TITLE
Package has no standard histoprint.__version__

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/histoprint#25]
I noticed this as I was going to include `histoprint` into `scikit-hep` and `skhep.show_versions()` threw the error
`AttributeError: module 'histoprint' has no attribute '__version__'` when I added `histoprint`.

**Comment by eduardo-rodrigues** [comment]
Let me know if you would like or not to have histoprint in the scikit-hep metapackage.

**Comment by ast0815** [comment]
I don't what that would entail. Is there any reason _not_ to have it being a part of it?

**Comment by eduardo-rodrigues** [comment]
Nothing more than being distributed via a `pip install scikit-hep`. It's a neat way to straightforwardly get a consistent installation of a whole bunch of project packages. I particularly like it for tutorials and notebook presentations since it makes the environment YAML file rather trivial. I will add `histoprint` soon, then.

**Comment by ast0815** [comment]
Sounds good. Thanks! :+1:
