### ISSUE TITLE
UHI support

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/histoprint#33]
I'd like for histoprint to also support UHI. What is the status of this?

For proper, type checked support, Python 3.6+ is much nicer. ;) I can pull out the utility added to mplhep in https://github.com/scikit-hep/mplhep/pull/251 as a way to accept all types of histograms (NumPy tuples and a few others, and PlottableProtocol histograms) and create a PlottableProtocol compatible view to it than then can be uniformly used afterwards (it's also Python 3.6+).

**Comment by henryiii** [comment]
That's what I was mentioning "moving" to the UHI repo, though it would be the other direction; that is, you'd accept NumPy tuples, old style boost-histograms (for now), and PlottableProtocol objects, but for "old" objects, you'd adapt them into PlottableProtocol conforming objects (A NumPyPlottableHistogram, IIRC the name in mplhep), then you'd use just the UHI parts as you've described above regardless of the original input.

The other direction works, but has two issues - you don't be able to get variances eventually if there's a reason to, and you won't be able to work with string / int category axes, only with continuous axes. In mplhep, I just skipped over category axes for now, so you'd not actually miss anything by going this direction for now, then changing later if you wanted to add one of these two things.

**Comment by ast0815** [comment]
I mean, for the plots I definitely need values and bin edges at the moment. That's what histoprint can plot. There is not much of an internal "data state" to speak of at the moment. I have some ideas for improvements where this would change though. For that I would probably go with a `PlottableProtocol` kind of histogram data representation. But right now I do not see how it would benefit `histoprint` to add an extra step of converting e.g. NumPy histograms into `PlottableProtocol` objects, just to get the bin edges and values out of it again. Though maybe I misunderstand what you would like to do.

I am also going to drop support for Python 2.7 soon.

**Comment by ast0815** [comment]
Do you have a suggestion how to best test the plotting of `PlottableProtocol` objects? I took a look at `boosthistogram` and `uproot` `TH1`s, but the methods I see in those do not correspond to what I read here: https://uhi.readthedocs.io/en/latest/plotting.html#using-the-protocol

**Comment by ast0815** [comment]
I have implemented something in #35. Does this cover your use cases for now, @henryiii? As mentioned, I have some improvements in mind to make things a bit more object oriented, but I don't know when I will have the time to work on this.

**Comment by ast0815** [comment]
Is this good enough for now, @henryiii? Or did you have more/something else in mind?

**Comment by ast0815** [comment]
If there is nothing else, I will close this issue for now.

**Comment by henryiii** [comment]
I would recommend using the UHI adaptor helpers in the `uhi` library, as you get a few free features for now (maybe TH1D support soon, etc), but yes, this was what was needed to support UHI.

**Comment by henryiii** [comment]
If you were using the UHI adaptor, you would have received free PyROOT support in the UHI 0.3.0 update. :)

**Comment by ast0815** [comment]
Like this? :P

https://github.com/scikit-hep/histoprint/blob/dab8c42de4f12e62f245c69d73f25e3cbae719e1/histoprint/formatter.py#L564

Or is there another method I should be using instead?

**Comment by henryiii** [comment]
Yes, that looks like it!
