### ISSUE TITLE
Mint DOIs to releases via Zenodo?

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/histoprint#46]
Have you thought about that? We do it for most of the org packages.

**Comment by ast0815** [comment]
I have not thought about it. I use Zenodo DOIs for another project of mine, so I am happy to do this here as well. Not sure this little printout library is important enough to ever be cited, but those DOIs are free, so might as well. 😄

**Comment by eduardo-rodrigues** [comment]
That's a bit the point. the community tries and improve on software recognition and citations but for that to happen the citations have to be available ;-).

**Comment by ast0815** [comment]
Should I do it with my Zenodo account then? Or do you have a scikit-hep one?

**Comment by eduardo-rodrigues** [comment]
We have a scikit-hep account for PyPI, and we try and get scikit-hep as a maintainer there, for better "coverage", but we do not have one for Zenodo and every author/maintainer sets up the webhook for their packages. This is quite OK I reckon.

**Comment by ast0815** [comment]
I tried to add this repo to Zenodo, but it does not show up. The FAQ says I need to be an admin of the repository or the organisation for this to work. I don't think I am either at the moment.

**Comment by eduardo-rodrigues** [comment]
That was strange. Indeed you were not admin for your package :S. I've just changed that. Can you retry and let me know?

**Comment by ast0815** [comment]
Yep, I have enabled histoprint now. The next release should get its own DOI, after which I will add the badge and close this issue. :+1:

**Comment by ast0815** [comment]
We now are citable. 🎈 🥳
